<?php declare(strict_types=1);

echo '<h1>Hello!</h1>';
echo sprintf('<h5>Phalcon ver: %s</h5>', (new Phalcon\Support\Version())->get());
echo sprintf('<h5>PHP ver: %s</h5>', \PHP_VERSION);

echo Phalcon\Tag::linkTo(['signup', 'Sign Up Here!', 'class' => 'btn btn-primary']);

/** @var $users App\Models\User */
if ($users->count() > 0) { ?>
    <hr class="my-3">
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Pass</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
            </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
                <td><?php echo $user->pass; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
